name = "PSPipePlanckRender"
uuid = "b1e2d088-1f9c-4abc-8edc-d415bc3cfb69"
authors = ["Zack Li"]
version = "0.1.2"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
